//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	trainerv1alpha1 "github.com/kubeflow/trainer/v2/pkg/apis/trainer/v1alpha1"
	corev1 "k8s.io/api/core/v1"
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppliedOverride) DeepCopyInto(out *AppliedOverride) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppliedOverride.
func (in *AppliedOverride) DeepCopy() *AppliedOverride {
	if in == nil {
		return nil
	}
	out := new(AppliedOverride)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BandwidthMeasurement) DeepCopyInto(out *BandwidthMeasurement) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BandwidthMeasurement.
func (in *BandwidthMeasurement) DeepCopy() *BandwidthMeasurement {
	if in == nil {
		return nil
	}
	out := new(BandwidthMeasurement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BandwidthMeasurement) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BandwidthMeasurementConfig) DeepCopyInto(out *BandwidthMeasurementConfig) {
	*out = *in
	if in.SampleInterval != nil {
		in, out := &in.SampleInterval, &out.SampleInterval
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BandwidthMeasurementConfig.
func (in *BandwidthMeasurementConfig) DeepCopy() *BandwidthMeasurementConfig {
	if in == nil {
		return nil
	}
	out := new(BandwidthMeasurementConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BandwidthMeasurementList) DeepCopyInto(out *BandwidthMeasurementList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BandwidthMeasurement, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BandwidthMeasurementList.
func (in *BandwidthMeasurementList) DeepCopy() *BandwidthMeasurementList {
	if in == nil {
		return nil
	}
	out := new(BandwidthMeasurementList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BandwidthMeasurementList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BandwidthMeasurementSpec) DeepCopyInto(out *BandwidthMeasurementSpec) {
	*out = *in
	in.JobRef.DeepCopyInto(&out.JobRef)
	if in.SampleInterval != nil {
		in, out := &in.SampleInterval, &out.SampleInterval
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BandwidthMeasurementSpec.
func (in *BandwidthMeasurementSpec) DeepCopy() *BandwidthMeasurementSpec {
	if in == nil {
		return nil
	}
	out := new(BandwidthMeasurementSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BandwidthMeasurementStatus) DeepCopyInto(out *BandwidthMeasurementStatus) {
	*out = *in
	if in.Results != nil {
		in, out := &in.Results, &out.Results
		*out = make([]BandwidthResult, len(*in))
		copy(*out, *in)
	}
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BandwidthMeasurementStatus.
func (in *BandwidthMeasurementStatus) DeepCopy() *BandwidthMeasurementStatus {
	if in == nil {
		return nil
	}
	out := new(BandwidthMeasurementStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BandwidthResult) DeepCopyInto(out *BandwidthResult) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BandwidthResult.
func (in *BandwidthResult) DeepCopy() *BandwidthResult {
	if in == nil {
		return nil
	}
	out := new(BandwidthResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CELNodeHealthCheck) DeepCopyInto(out *CELNodeHealthCheck) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CELNodeHealthCheck.
func (in *CELNodeHealthCheck) DeepCopy() *CELNodeHealthCheck {
	if in == nil {
		return nil
	}
	out := new(CELNodeHealthCheck)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CategoryOptions) DeepCopyInto(out *CategoryOptions) {
	*out = *in
	if in.NodesPerJob != nil {
		in, out := &in.NodesPerJob, &out.NodesPerJob
		*out = new(int32)
		**out = **in
	}
	if in.EnableCheckpoint != nil {
		in, out := &in.EnableCheckpoint, &out.EnableCheckpoint
		*out = new(bool)
		**out = **in
	}
	if in.MaxSteps != nil {
		in, out := &in.MaxSteps, &out.MaxSteps
		*out = new(int32)
		**out = **in
	}
	if in.ExitDurationMins != nil {
		in, out := &in.ExitDurationMins, &out.ExitDurationMins
		*out = new(int32)
		**out = **in
	}
	if in.StartupStallTimeoutSeconds != nil {
		in, out := &in.StartupStallTimeoutSeconds, &out.StartupStallTimeoutSeconds
		*out = new(int32)
		**out = **in
	}
	if in.GpusPerNode != nil {
		in, out := &in.GpusPerNode, &out.GpusPerNode
		*out = new(int32)
		**out = **in
	}
	if in.MlnxPerNode != nil {
		in, out := &in.MlnxPerNode, &out.MlnxPerNode
		*out = new(int32)
		**out = **in
	}
	if in.NicResourceName != nil {
		in, out := &in.NicResourceName, &out.NicResourceName
		*out = new(string)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(CategoryResources)
		(*in).DeepCopyInto(*out)
	}
	if in.EnableMNNVL != nil {
		in, out := &in.EnableMNNVL, &out.EnableMNNVL
		*out = new(bool)
		**out = **in
	}
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]corev1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.StorageClassName != nil {
		in, out := &in.StorageClassName, &out.StorageClassName
		*out = new(string)
		**out = **in
	}
	if in.SaveInterval != nil {
		in, out := &in.SaveInterval, &out.SaveInterval
		*out = new(int32)
		**out = **in
	}
	if in.SaveRetainInterval != nil {
		in, out := &in.SaveRetainInterval, &out.SaveRetainInterval
		*out = new(int32)
		**out = **in
	}
	if in.SaveTopK != nil {
		in, out := &in.SaveTopK, &out.SaveTopK
		*out = new(int32)
		**out = **in
	}
	if in.MaxRestarts != nil {
		in, out := &in.MaxRestarts, &out.MaxRestarts
		*out = new(int32)
		**out = **in
	}
	if in.RepeatCount != nil {
		in, out := &in.RepeatCount, &out.RepeatCount
		*out = new(int32)
		**out = **in
	}
	if in.NumIterations != nil {
		in, out := &in.NumIterations, &out.NumIterations
		*out = new(int32)
		**out = **in
	}
	if in.NumCycles != nil {
		in, out := &in.NumCycles, &out.NumCycles
		*out = new(int32)
		**out = **in
	}
	if in.Thresholds != nil {
		in, out := &in.Thresholds, &out.Thresholds
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.MaxConcurrent != nil {
		in, out := &in.MaxConcurrent, &out.MaxConcurrent
		*out = new(int32)
		**out = **in
	}
	if in.MinGroupSize != nil {
		in, out := &in.MinGroupSize, &out.MinGroupSize
		*out = new(int32)
		**out = **in
	}
	if in.WorkloadMetadata != nil {
		in, out := &in.WorkloadMetadata, &out.WorkloadMetadata
		*out = new(WorkloadMetadata)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CategoryOptions.
func (in *CategoryOptions) DeepCopy() *CategoryOptions {
	if in == nil {
		return nil
	}
	out := new(CategoryOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CategoryResourceList) DeepCopyInto(out *CategoryResourceList) {
	*out = *in
	if in.CPU != nil {
		in, out := &in.CPU, &out.CPU
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.Memory != nil {
		in, out := &in.Memory, &out.Memory
		x := (*in).DeepCopy()
		*out = &x
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CategoryResourceList.
func (in *CategoryResourceList) DeepCopy() *CategoryResourceList {
	if in == nil {
		return nil
	}
	out := new(CategoryResourceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CategoryResources) DeepCopyInto(out *CategoryResources) {
	*out = *in
	if in.Limits != nil {
		in, out := &in.Limits, &out.Limits
		*out = new(CategoryResourceList)
		(*in).DeepCopyInto(*out)
	}
	if in.Requests != nil {
		in, out := &in.Requests, &out.Requests
		*out = new(CategoryResourceList)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CategoryResources.
func (in *CategoryResources) DeepCopy() *CategoryResources {
	if in == nil {
		return nil
	}
	out := new(CategoryResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateCategory) DeepCopyInto(out *CertificateCategory) {
	*out = *in
	if in.Options != nil {
		in, out := &in.Options, &out.Options
		*out = new(CategoryOptions)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateCategory.
func (in *CertificateCategory) DeepCopy() *CertificateCategory {
	if in == nil {
		return nil
	}
	out := new(CertificateCategory)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Certification) DeepCopyInto(out *Certification) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Certification.
func (in *Certification) DeepCopy() *Certification {
	if in == nil {
		return nil
	}
	out := new(Certification)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Certification) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificationCategoryStatus) DeepCopyInto(out *CertificationCategoryStatus) {
	*out = *in
	if in.WorkflowRef != nil {
		in, out := &in.WorkflowRef, &out.WorkflowRef
		*out = new(WorkflowReference)
		**out = **in
	}
	if in.SucceededNodesRef != nil {
		in, out := &in.SucceededNodesRef, &out.SucceededNodesRef
		*out = new(corev1.TypedLocalObjectReference)
		(*in).DeepCopyInto(*out)
	}
	if in.FailedNodesRef != nil {
		in, out := &in.FailedNodesRef, &out.FailedNodesRef
		*out = new(corev1.TypedLocalObjectReference)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificationCategoryStatus.
func (in *CertificationCategoryStatus) DeepCopy() *CertificationCategoryStatus {
	if in == nil {
		return nil
	}
	out := new(CertificationCategoryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificationList) DeepCopyInto(out *CertificationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Certification, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificationList.
func (in *CertificationList) DeepCopy() *CertificationList {
	if in == nil {
		return nil
	}
	out := new(CertificationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CertificationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificationSpec) DeepCopyInto(out *CertificationSpec) {
	*out = *in
	in.Target.DeepCopyInto(&out.Target)
	if in.Categories != nil {
		in, out := &in.Categories, &out.Categories
		*out = make([]CertificateCategory, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.GangScheduler != nil {
		in, out := &in.GangScheduler, &out.GangScheduler
		*out = new(GangSchedulerSpec)
		**out = **in
	}
	in.CategoryOptions.DeepCopyInto(&out.CategoryOptions)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificationSpec.
func (in *CertificationSpec) DeepCopy() *CertificationSpec {
	if in == nil {
		return nil
	}
	out := new(CertificationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificationStatus) DeepCopyInto(out *CertificationStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CategoryStatuses != nil {
		in, out := &in.CategoryStatuses, &out.CategoryStatuses
		*out = make([]CertificationCategoryStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificationStatus.
func (in *CertificationStatus) DeepCopy() *CertificationStatus {
	if in == nil {
		return nil
	}
	out := new(CertificationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CheckpointConfig) DeepCopyInto(out *CheckpointConfig) {
	*out = *in
	if in.MaxRestarts != nil {
		in, out := &in.MaxRestarts, &out.MaxRestarts
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CheckpointConfig.
func (in *CheckpointConfig) DeepCopy() *CheckpointConfig {
	if in == nil {
		return nil
	}
	out := new(CheckpointConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CrossBoundaryProbe) DeepCopyInto(out *CrossBoundaryProbe) {
	*out = *in
	if in.HalfA != nil {
		in, out := &in.HalfA, &out.HalfA
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.HalfB != nil {
		in, out := &in.HalfB, &out.HalfB
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CrossBoundaryProbe.
func (in *CrossBoundaryProbe) DeepCopy() *CrossBoundaryProbe {
	if in == nil {
		return nil
	}
	out := new(CrossBoundaryProbe)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CrossBoundaryState) DeepCopyInto(out *CrossBoundaryState) {
	*out = *in
	if in.PendingProbes != nil {
		in, out := &in.PendingProbes, &out.PendingProbes
		*out = make([]CrossBoundaryProbe, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CrossBoundaryState.
func (in *CrossBoundaryState) DeepCopy() *CrossBoundaryState {
	if in == nil {
		return nil
	}
	out := new(CrossBoundaryState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DependencyResourceRef) DeepCopyInto(out *DependencyResourceRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DependencyResourceRef.
func (in *DependencyResourceRef) DeepCopy() *DependencyResourceRef {
	if in == nil {
		return nil
	}
	out := new(DependencyResourceRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DependencySpec) DeepCopyInto(out *DependencySpec) {
	*out = *in
	in.RawExtension.DeepCopyInto(&out.RawExtension)
	in.When.DeepCopyInto(&out.When)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DependencySpec.
func (in *DependencySpec) DeepCopy() *DependencySpec {
	if in == nil {
		return nil
	}
	out := new(DependencySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiagnoseSpec) DeepCopyInto(out *DiagnoseSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiagnoseSpec.
func (in *DiagnoseSpec) DeepCopy() *DiagnoseSpec {
	if in == nil {
		return nil
	}
	out := new(DiagnoseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiagnoseStatus) DeepCopyInto(out *DiagnoseStatus) {
	*out = *in
	if in.HealthyNodes != nil {
		in, out := &in.HealthyNodes, &out.HealthyNodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SuspectNodes != nil {
		in, out := &in.SuspectNodes, &out.SuspectNodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.NoNVLSuspectNodes != nil {
		in, out := &in.NoNVLSuspectNodes, &out.NoNVLSuspectNodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RepresentativeNodes != nil {
		in, out := &in.RepresentativeNodes, &out.RepresentativeNodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ScreeningResults != nil {
		in, out := &in.ScreeningResults, &out.ScreeningResults
		*out = make(map[string]DomainScreeningResult, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.NoNVLScreeningResults != nil {
		in, out := &in.NoNVLScreeningResults, &out.NoNVLScreeningResults
		*out = make(map[string]DomainScreeningResult, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.InfrastructureFaults != nil {
		in, out := &in.InfrastructureFaults, &out.InfrastructureFaults
		*out = make([]InfrastructureFault, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CrossBoundaryState != nil {
		in, out := &in.CrossBoundaryState, &out.CrossBoundaryState
		*out = new(CrossBoundaryState)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiagnoseStatus.
func (in *DiagnoseStatus) DeepCopy() *DiagnoseStatus {
	if in == nil {
		return nil
	}
	out := new(DiagnoseStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DomainResult) DeepCopyInto(out *DomainResult) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DomainResult.
func (in *DomainResult) DeepCopy() *DomainResult {
	if in == nil {
		return nil
	}
	out := new(DomainResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DomainScreeningResult) DeepCopyInto(out *DomainScreeningResult) {
	*out = *in
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DomainScreeningResult.
func (in *DomainScreeningResult) DeepCopy() *DomainScreeningResult {
	if in == nil {
		return nil
	}
	out := new(DomainScreeningResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventPattern) DeepCopyInto(out *EventPattern) {
	*out = *in
	if in.Units != nil {
		in, out := &in.Units, &out.Units
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventPattern.
func (in *EventPattern) DeepCopy() *EventPattern {
	if in == nil {
		return nil
	}
	out := new(EventPattern)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExecFramework) DeepCopyInto(out *ExecFramework) {
	*out = *in
	if in.Command != nil {
		in, out := &in.Command, &out.Command
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExecFramework.
func (in *ExecFramework) DeepCopy() *ExecFramework {
	if in == nil {
		return nil
	}
	out := new(ExecFramework)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExecutionSpec) DeepCopyInto(out *ExecutionSpec) {
	*out = *in
	if in.TimeoutPerJob != nil {
		in, out := &in.TimeoutPerJob, &out.TimeoutPerJob
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExecutionSpec.
func (in *ExecutionSpec) DeepCopy() *ExecutionSpec {
	if in == nil {
		return nil
	}
	out := new(ExecutionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FailedNode) DeepCopyInto(out *FailedNode) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FailedNode.
func (in *FailedNode) DeepCopy() *FailedNode {
	if in == nil {
		return nil
	}
	out := new(FailedNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FailureLog) DeepCopyInto(out *FailureLog) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FailureLog.
func (in *FailureLog) DeepCopy() *FailureLog {
	if in == nil {
		return nil
	}
	out := new(FailureLog)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FrameworkSpec) DeepCopyInto(out *FrameworkSpec) {
	*out = *in
	if in.Torch != nil {
		in, out := &in.Torch, &out.Torch
		*out = new(TorchFramework)
		(*in).DeepCopyInto(*out)
	}
	if in.MPI != nil {
		in, out := &in.MPI, &out.MPI
		*out = new(MPIFramework)
		(*in).DeepCopyInto(*out)
	}
	if in.Exec != nil {
		in, out := &in.Exec, &out.Exec
		*out = new(ExecFramework)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FrameworkSpec.
func (in *FrameworkSpec) DeepCopy() *FrameworkSpec {
	if in == nil {
		return nil
	}
	out := new(FrameworkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GangSchedulerSpec) DeepCopyInto(out *GangSchedulerSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GangSchedulerSpec.
func (in *GangSchedulerSpec) DeepCopy() *GangSchedulerSpec {
	if in == nil {
		return nil
	}
	out := new(GangSchedulerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GoodputMeasurement) DeepCopyInto(out *GoodputMeasurement) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GoodputMeasurement.
func (in *GoodputMeasurement) DeepCopy() *GoodputMeasurement {
	if in == nil {
		return nil
	}
	out := new(GoodputMeasurement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GoodputMeasurement) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GoodputMeasurementConfig) DeepCopyInto(out *GoodputMeasurementConfig) {
	*out = *in
	if in.SampleInterval != nil {
		in, out := &in.SampleInterval, &out.SampleInterval
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GoodputMeasurementConfig.
func (in *GoodputMeasurementConfig) DeepCopy() *GoodputMeasurementConfig {
	if in == nil {
		return nil
	}
	out := new(GoodputMeasurementConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GoodputMeasurementList) DeepCopyInto(out *GoodputMeasurementList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GoodputMeasurement, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GoodputMeasurementList.
func (in *GoodputMeasurementList) DeepCopy() *GoodputMeasurementList {
	if in == nil {
		return nil
	}
	out := new(GoodputMeasurementList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GoodputMeasurementList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GoodputMeasurementSpec) DeepCopyInto(out *GoodputMeasurementSpec) {
	*out = *in
	in.JobRef.DeepCopyInto(&out.JobRef)
	if in.SampleInterval != nil {
		in, out := &in.SampleInterval, &out.SampleInterval
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GoodputMeasurementSpec.
func (in *GoodputMeasurementSpec) DeepCopy() *GoodputMeasurementSpec {
	if in == nil {
		return nil
	}
	out := new(GoodputMeasurementSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GoodputMeasurementStatus) DeepCopyInto(out *GoodputMeasurementStatus) {
	*out = *in
	if in.LastCheckpointTime != nil {
		in, out := &in.LastCheckpointTime, &out.LastCheckpointTime
		*out = (*in).DeepCopy()
	}
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
	if in.LastStepTimestamp != nil {
		in, out := &in.LastStepTimestamp, &out.LastStepTimestamp
		*out = (*in).DeepCopy()
	}
	if in.WarmupBaseStep != nil {
		in, out := &in.WarmupBaseStep, &out.WarmupBaseStep
		*out = new(int)
		**out = **in
	}
	if in.ApplicationStartTime != nil {
		in, out := &in.ApplicationStartTime, &out.ApplicationStartTime
		*out = (*in).DeepCopy()
	}
	if in.ApplicationStopTime != nil {
		in, out := &in.ApplicationStopTime, &out.ApplicationStopTime
		*out = (*in).DeepCopy()
	}
	if in.PendingInterruption != nil {
		in, out := &in.PendingInterruption, &out.PendingInterruption
		*out = new(PendingInterruptionStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GoodputMeasurementStatus.
func (in *GoodputMeasurementStatus) DeepCopy() *GoodputMeasurementStatus {
	if in == nil {
		return nil
	}
	out := new(GoodputMeasurementStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroupIterationResult) DeepCopyInto(out *GroupIterationResult) {
	*out = *in
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroupIterationResult.
func (in *GroupIterationResult) DeepCopy() *GroupIterationResult {
	if in == nil {
		return nil
	}
	out := new(GroupIterationResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroupStatus) DeepCopyInto(out *GroupStatus) {
	*out = *in
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Domains != nil {
		in, out := &in.Domains, &out.Domains
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DomainNodeCounts != nil {
		in, out := &in.DomainNodeCounts, &out.DomainNodeCounts
		*out = make(map[string]int, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.JobRef != nil {
		in, out := &in.JobRef, &out.JobRef
		*out = new(WorkloadReference)
		**out = **in
	}
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroupStatus.
func (in *GroupStatus) DeepCopy() *GroupStatus {
	if in == nil {
		return nil
	}
	out := new(GroupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfrastructureFault) DeepCopyInto(out *InfrastructureFault) {
	*out = *in
	if in.GroupA != nil {
		in, out := &in.GroupA, &out.GroupA
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.GroupB != nil {
		in, out := &in.GroupB, &out.GroupB
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfrastructureFault.
func (in *InfrastructureFault) DeepCopy() *InfrastructureFault {
	if in == nil {
		return nil
	}
	out := new(InfrastructureFault)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntMatchSpec) DeepCopyInto(out *IntMatchSpec) {
	*out = *in
	if in.Equals != nil {
		in, out := &in.Equals, &out.Equals
		*out = new(int)
		**out = **in
	}
	if in.GreaterThan != nil {
		in, out := &in.GreaterThan, &out.GreaterThan
		*out = new(int)
		**out = **in
	}
	if in.LessThan != nil {
		in, out := &in.LessThan, &out.LessThan
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntMatchSpec.
func (in *IntMatchSpec) DeepCopy() *IntMatchSpec {
	if in == nil {
		return nil
	}
	out := new(IntMatchSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IterationMetrics) DeepCopyInto(out *IterationMetrics) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IterationMetrics.
func (in *IterationMetrics) DeepCopy() *IterationMetrics {
	if in == nil {
		return nil
	}
	out := new(IterationMetrics)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IterationResult) DeepCopyInto(out *IterationResult) {
	*out = *in
	if in.Groups != nil {
		in, out := &in.Groups, &out.Groups
		*out = make([]GroupIterationResult, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IterationResult.
func (in *IterationResult) DeepCopy() *IterationResult {
	if in == nil {
		return nil
	}
	out := new(IterationResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Job) DeepCopyInto(out *Job) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Job.
func (in *Job) DeepCopy() *Job {
	if in == nil {
		return nil
	}
	out := new(Job)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Job) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JobList) DeepCopyInto(out *JobList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Job, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JobList.
func (in *JobList) DeepCopy() *JobList {
	if in == nil {
		return nil
	}
	out := new(JobList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *JobList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JobSpec) DeepCopyInto(out *JobSpec) {
	*out = *in
	in.Workload.DeepCopyInto(&out.Workload)
	if in.WorkloadMetadata != nil {
		in, out := &in.WorkloadMetadata, &out.WorkloadMetadata
		*out = new(WorkloadMetadata)
		(*in).DeepCopyInto(*out)
	}
	if in.NodeHealthMonitor != nil {
		in, out := &in.NodeHealthMonitor, &out.NodeHealthMonitor
		*out = new(NodeHealthMonitor)
		(*in).DeepCopyInto(*out)
	}
	if in.Checkpoint != nil {
		in, out := &in.Checkpoint, &out.Checkpoint
		*out = new(CheckpointConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.StallMultiplier != nil {
		in, out := &in.StallMultiplier, &out.StallMultiplier
		*out = new(int32)
		**out = **in
	}
	if in.StartupStallTimeoutSeconds != nil {
		in, out := &in.StartupStallTimeoutSeconds, &out.StartupStallTimeoutSeconds
		*out = new(int32)
		**out = **in
	}
	if in.GoodputMeasurement != nil {
		in, out := &in.GoodputMeasurement, &out.GoodputMeasurement
		*out = new(GoodputMeasurementConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.BandwidthMeasurement != nil {
		in, out := &in.BandwidthMeasurement, &out.BandwidthMeasurement
		*out = new(BandwidthMeasurementConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Thresholds != nil {
		in, out := &in.Thresholds, &out.Thresholds
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.MeasurementTimeout != nil {
		in, out := &in.MeasurementTimeout, &out.MeasurementTimeout
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JobSpec.
func (in *JobSpec) DeepCopy() *JobSpec {
	if in == nil {
		return nil
	}
	out := new(JobSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JobStatus) DeepCopyInto(out *JobStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.FailedNodes != nil {
		in, out := &in.FailedNodes, &out.FailedNodes
		*out = make([]FailedNode, len(*in))
		copy(*out, *in)
	}
	if in.WorkloadRef != nil {
		in, out := &in.WorkloadRef, &out.WorkloadRef
		*out = new(WorkloadReference)
		**out = **in
	}
	if in.WorkloadStartTime != nil {
		in, out := &in.WorkloadStartTime, &out.WorkloadStartTime
		*out = (*in).DeepCopy()
	}
	if in.FailureLog != nil {
		in, out := &in.FailureLog, &out.FailureLog
		*out = new(FailureLog)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JobStatus.
func (in *JobStatus) DeepCopy() *JobStatus {
	if in == nil {
		return nil
	}
	out := new(JobStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JobTemplateSpec) DeepCopyInto(out *JobTemplateSpec) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JobTemplateSpec.
func (in *JobTemplateSpec) DeepCopy() *JobTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(JobTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogPatternSet) DeepCopyInto(out *LogPatternSet) {
	*out = *in
	if in.TrainingStep != nil {
		in, out := &in.TrainingStep, &out.TrainingStep
		*out = new(EventPattern)
		(*in).DeepCopyInto(*out)
	}
	if in.CheckpointSave != nil {
		in, out := &in.CheckpointSave, &out.CheckpointSave
		*out = new(EventPattern)
		(*in).DeepCopyInto(*out)
	}
	if in.CheckpointDone != nil {
		in, out := &in.CheckpointDone, &out.CheckpointDone
		*out = new(EventPattern)
		(*in).DeepCopyInto(*out)
	}
	if in.CheckpointRestore != nil {
		in, out := &in.CheckpointRestore, &out.CheckpointRestore
		*out = new(EventPattern)
		(*in).DeepCopyInto(*out)
	}
	if in.CheckpointLoaded != nil {
		in, out := &in.CheckpointLoaded, &out.CheckpointLoaded
		*out = new(EventPattern)
		(*in).DeepCopyInto(*out)
	}
	if in.ApplicationStart != nil {
		in, out := &in.ApplicationStart, &out.ApplicationStart
		*out = new(EventPattern)
		(*in).DeepCopyInto(*out)
	}
	if in.WarmupStep != nil {
		in, out := &in.WarmupStep, &out.WarmupStep
		*out = new(EventPattern)
		(*in).DeepCopyInto(*out)
	}
	if in.BandwidthResult != nil {
		in, out := &in.BandwidthResult, &out.BandwidthResult
		*out = new(EventPattern)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogPatternSet.
func (in *LogPatternSet) DeepCopy() *LogPatternSet {
	if in == nil {
		return nil
	}
	out := new(LogPatternSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogProfile) DeepCopyInto(out *LogProfile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogProfile.
func (in *LogProfile) DeepCopy() *LogProfile {
	if in == nil {
		return nil
	}
	out := new(LogProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LogProfile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogProfileList) DeepCopyInto(out *LogProfileList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LogProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogProfileList.
func (in *LogProfileList) DeepCopy() *LogProfileList {
	if in == nil {
		return nil
	}
	out := new(LogProfileList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LogProfileList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogProfileSpec) DeepCopyInto(out *LogProfileSpec) {
	*out = *in
	out.Timestamp = in.Timestamp
	in.Patterns.DeepCopyInto(&out.Patterns)
	if in.WorkerStrategy != nil {
		in, out := &in.WorkerStrategy, &out.WorkerStrategy
		*out = new(WorkerStrategySpec)
		**out = **in
	}
	if in.WarmupSteps != nil {
		in, out := &in.WarmupSteps, &out.WarmupSteps
		*out = new(int)
		**out = **in
	}
	if in.LogInterval != nil {
		in, out := &in.LogInterval, &out.LogInterval
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogProfileSpec.
func (in *LogProfileSpec) DeepCopy() *LogProfileSpec {
	if in == nil {
		return nil
	}
	out := new(LogProfileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MPIFramework) DeepCopyInto(out *MPIFramework) {
	*out = *in
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.MpiArgs != nil {
		in, out := &in.MpiArgs, &out.MpiArgs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MPIFramework.
func (in *MPIFramework) DeepCopy() *MPIFramework {
	if in == nil {
		return nil
	}
	out := new(MPIFramework)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeHealthMonitor) DeepCopyInto(out *NodeHealthMonitor) {
	*out = *in
	if in.CEL != nil {
		in, out := &in.CEL, &out.CEL
		*out = new(CELNodeHealthCheck)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeHealthMonitor.
func (in *NodeHealthMonitor) DeepCopy() *NodeHealthMonitor {
	if in == nil {
		return nil
	}
	out := new(NodeHealthMonitor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeResult) DeepCopyInto(out *NodeResult) {
	*out = *in
	if in.Iterations != nil {
		in, out := &in.Iterations, &out.Iterations
		*out = make([]IterationMetrics, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeResult.
func (in *NodeResult) DeepCopy() *NodeResult {
	if in == nil {
		return nil
	}
	out := new(NodeResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrchestrationOverrideSpec) DeepCopyInto(out *OrchestrationOverrideSpec) {
	*out = *in
	if in.Target != nil {
		in, out := &in.Target, &out.Target
		*out = new(TargetSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Topology != nil {
		in, out := &in.Topology, &out.Topology
		*out = new(TopologySpec)
		**out = **in
	}
	if in.Execution != nil {
		in, out := &in.Execution, &out.Execution
		*out = new(ExecutionSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Iterations != nil {
		in, out := &in.Iterations, &out.Iterations
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrchestrationOverrideSpec.
func (in *OrchestrationOverrideSpec) DeepCopy() *OrchestrationOverrideSpec {
	if in == nil {
		return nil
	}
	out := new(OrchestrationOverrideSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrchestrationSpec) DeepCopyInto(out *OrchestrationSpec) {
	*out = *in
	if in.Target != nil {
		in, out := &in.Target, &out.Target
		*out = new(TargetSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Topology != nil {
		in, out := &in.Topology, &out.Topology
		*out = new(TopologySpec)
		**out = **in
	}
	if in.Diagnose != nil {
		in, out := &in.Diagnose, &out.Diagnose
		*out = new(DiagnoseSpec)
		**out = **in
	}
	in.Execution.DeepCopyInto(&out.Execution)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrchestrationSpec.
func (in *OrchestrationSpec) DeepCopy() *OrchestrationSpec {
	if in == nil {
		return nil
	}
	out := new(OrchestrationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrchestrationStatus) DeepCopyInto(out *OrchestrationStatus) {
	*out = *in
	if in.IterationHistory != nil {
		in, out := &in.IterationHistory, &out.IterationHistory
		*out = make([]IterationResult, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ExcludedNodes != nil {
		in, out := &in.ExcludedNodes, &out.ExcludedNodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AppliedOverrides != nil {
		in, out := &in.AppliedOverrides, &out.AppliedOverrides
		*out = make([]AppliedOverride, len(*in))
		copy(*out, *in)
	}
	if in.Diagnose != nil {
		in, out := &in.Diagnose, &out.Diagnose
		*out = new(DiagnoseStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Groups != nil {
		in, out := &in.Groups, &out.Groups
		*out = make([]GroupStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrchestrationStatus.
func (in *OrchestrationStatus) DeepCopy() *OrchestrationStatus {
	if in == nil {
		return nil
	}
	out := new(OrchestrationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OverrideSpec) DeepCopyInto(out *OverrideSpec) {
	*out = *in
	in.When.DeepCopyInto(&out.When)
	if in.JobTemplate != nil {
		in, out := &in.JobTemplate, &out.JobTemplate
		*out = new(apiextensionsv1.JSON)
		(*in).DeepCopyInto(*out)
	}
	if in.JobTemplatePatch != nil {
		in, out := &in.JobTemplatePatch, &out.JobTemplatePatch
		*out = new(apiextensionsv1.JSON)
		(*in).DeepCopyInto(*out)
	}
	if in.Dependencies != nil {
		in, out := &in.Dependencies, &out.Dependencies
		*out = make([]DependencySpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Orchestration != nil {
		in, out := &in.Orchestration, &out.Orchestration
		*out = new(OrchestrationOverrideSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OverrideSpec.
func (in *OverrideSpec) DeepCopy() *OverrideSpec {
	if in == nil {
		return nil
	}
	out := new(OverrideSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PendingInterruptionStatus) DeepCopyInto(out *PendingInterruptionStatus) {
	*out = *in
	if in.TCheckpoint != nil {
		in, out := &in.TCheckpoint, &out.TCheckpoint
		*out = (*in).DeepCopy()
	}
	if in.TInterrupt != nil {
		in, out := &in.TInterrupt, &out.TInterrupt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PendingInterruptionStatus.
func (in *PendingInterruptionStatus) DeepCopy() *PendingInterruptionStatus {
	if in == nil {
		return nil
	}
	out := new(PendingInterruptionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PerformanceValidationSpec) DeepCopyInto(out *PerformanceValidationSpec) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(apiextensionsv1.JSON)
		(*in).DeepCopyInto(*out)
	}
	out.Tracking = in.Tracking
	if in.Thresholds != nil {
		in, out := &in.Thresholds, &out.Thresholds
		*out = new(ThresholdSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.MeasurementTimeout != nil {
		in, out := &in.MeasurementTimeout, &out.MeasurementTimeout
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PerformanceValidationSpec.
func (in *PerformanceValidationSpec) DeepCopy() *PerformanceValidationSpec {
	if in == nil {
		return nil
	}
	out := new(PerformanceValidationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StringMatchSpec) DeepCopyInto(out *StringMatchSpec) {
	*out = *in
	if in.In != nil {
		in, out := &in.In, &out.In
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.NotIn != nil {
		in, out := &in.NotIn, &out.NotIn
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StringMatchSpec.
func (in *StringMatchSpec) DeepCopy() *StringMatchSpec {
	if in == nil {
		return nil
	}
	out := new(StringMatchSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaintSelector) DeepCopyInto(out *TaintSelector) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaintSelector.
func (in *TaintSelector) DeepCopy() *TaintSelector {
	if in == nil {
		return nil
	}
	out := new(TaintSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetSpec) DeepCopyInto(out *TargetSpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.MatchExpressions != nil {
		in, out := &in.MatchExpressions, &out.MatchExpressions
		*out = make([]corev1.NodeSelectorRequirement, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NodeNames != nil {
		in, out := &in.NodeNames, &out.NodeNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.TaintSelectors != nil {
		in, out := &in.TaintSelectors, &out.TaintSelectors
		*out = make([]TaintSelector, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetSpec.
func (in *TargetSpec) DeepCopy() *TargetSpec {
	if in == nil {
		return nil
	}
	out := new(TargetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThresholdSpec) DeepCopyInto(out *ThresholdSpec) {
	*out = *in
	if in.Thresholds != nil {
		in, out := &in.Thresholds, &out.Thresholds
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThresholdSpec.
func (in *ThresholdSpec) DeepCopy() *ThresholdSpec {
	if in == nil {
		return nil
	}
	out := new(ThresholdSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimestampSpec) DeepCopyInto(out *TimestampSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimestampSpec.
func (in *TimestampSpec) DeepCopy() *TimestampSpec {
	if in == nil {
		return nil
	}
	out := new(TimestampSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopologyMatchSpec) DeepCopyInto(out *TopologyMatchSpec) {
	*out = *in
	if in.DomainCount != nil {
		in, out := &in.DomainCount, &out.DomainCount
		*out = new(IntMatchSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopologyMatchSpec.
func (in *TopologyMatchSpec) DeepCopy() *TopologyMatchSpec {
	if in == nil {
		return nil
	}
	out := new(TopologyMatchSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopologySpec) DeepCopyInto(out *TopologySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopologySpec.
func (in *TopologySpec) DeepCopy() *TopologySpec {
	if in == nil {
		return nil
	}
	out := new(TopologySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TorchFramework) DeepCopyInto(out *TorchFramework) {
	*out = *in
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TorchFramework.
func (in *TorchFramework) DeepCopy() *TorchFramework {
	if in == nil {
		return nil
	}
	out := new(TorchFramework)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrackingSpec) DeepCopyInto(out *TrackingSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrackingSpec.
func (in *TrackingSpec) DeepCopy() *TrackingSpec {
	if in == nil {
		return nil
	}
	out := new(TrackingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValidationSpec) DeepCopyInto(out *ValidationSpec) {
	*out = *in
	if in.Performance != nil {
		in, out := &in.Performance, &out.Performance
		*out = new(PerformanceValidationSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValidationSpec.
func (in *ValidationSpec) DeepCopy() *ValidationSpec {
	if in == nil {
		return nil
	}
	out := new(ValidationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WhenSpec) DeepCopyInto(out *WhenSpec) {
	*out = *in
	if in.GPUArchitecture != nil {
		in, out := &in.GPUArchitecture, &out.GPUArchitecture
		*out = new(StringMatchSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Platform != nil {
		in, out := &in.Platform, &out.Platform
		*out = new(StringMatchSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Topology != nil {
		in, out := &in.Topology, &out.Topology
		*out = new(TopologyMatchSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(apiextensionsv1.JSON)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WhenSpec.
func (in *WhenSpec) DeepCopy() *WhenSpec {
	if in == nil {
		return nil
	}
	out := new(WhenSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkerStrategySpec) DeepCopyInto(out *WorkerStrategySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkerStrategySpec.
func (in *WorkerStrategySpec) DeepCopy() *WorkerStrategySpec {
	if in == nil {
		return nil
	}
	out := new(WorkerStrategySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Workflow) DeepCopyInto(out *Workflow) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Workflow.
func (in *Workflow) DeepCopy() *Workflow {
	if in == nil {
		return nil
	}
	out := new(Workflow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Workflow) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkflowList) DeepCopyInto(out *WorkflowList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Workflow, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkflowList.
func (in *WorkflowList) DeepCopy() *WorkflowList {
	if in == nil {
		return nil
	}
	out := new(WorkflowList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WorkflowList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkflowReference) DeepCopyInto(out *WorkflowReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkflowReference.
func (in *WorkflowReference) DeepCopy() *WorkflowReference {
	if in == nil {
		return nil
	}
	out := new(WorkflowReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkflowSpec) DeepCopyInto(out *WorkflowSpec) {
	*out = *in
	in.JobTemplate.DeepCopyInto(&out.JobTemplate)
	in.Orchestration.DeepCopyInto(&out.Orchestration)
	if in.Dependencies != nil {
		in, out := &in.Dependencies, &out.Dependencies
		*out = make([]DependencySpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Overrides != nil {
		in, out := &in.Overrides, &out.Overrides
		*out = make([]OverrideSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Validation != nil {
		in, out := &in.Validation, &out.Validation
		*out = new(ValidationSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.GangScheduler != nil {
		in, out := &in.GangScheduler, &out.GangScheduler
		*out = new(GangSchedulerSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkflowSpec.
func (in *WorkflowSpec) DeepCopy() *WorkflowSpec {
	if in == nil {
		return nil
	}
	out := new(WorkflowSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkflowStatus) DeepCopyInto(out *WorkflowStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SucceededNodesRef != nil {
		in, out := &in.SucceededNodesRef, &out.SucceededNodesRef
		*out = new(corev1.TypedLocalObjectReference)
		(*in).DeepCopyInto(*out)
	}
	if in.FailedNodesRef != nil {
		in, out := &in.FailedNodesRef, &out.FailedNodesRef
		*out = new(corev1.TypedLocalObjectReference)
		(*in).DeepCopyInto(*out)
	}
	if in.DependencyRefs != nil {
		in, out := &in.DependencyRefs, &out.DependencyRefs
		*out = make([]DependencyResourceRef, len(*in))
		copy(*out, *in)
	}
	if in.Orchestration != nil {
		in, out := &in.Orchestration, &out.Orchestration
		*out = new(OrchestrationStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.NodeResults != nil {
		in, out := &in.NodeResults, &out.NodeResults
		*out = make(map[string]NodeResult, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.DomainResults != nil {
		in, out := &in.DomainResults, &out.DomainResults
		*out = make(map[string]DomainResult, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkflowStatus.
func (in *WorkflowStatus) DeepCopy() *WorkflowStatus {
	if in == nil {
		return nil
	}
	out := new(WorkflowStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadConfig) DeepCopyInto(out *WorkloadConfig) {
	*out = *in
	if in.Inline != nil {
		in, out := &in.Inline, &out.Inline
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ConfigMapRef != nil {
		in, out := &in.ConfigMapRef, &out.ConfigMapRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadConfig.
func (in *WorkloadConfig) DeepCopy() *WorkloadConfig {
	if in == nil {
		return nil
	}
	out := new(WorkloadConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadMetadata) DeepCopyInto(out *WorkloadMetadata) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]WorkloadLabelValue, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadMetadata.
func (in *WorkloadMetadata) DeepCopy() *WorkloadMetadata {
	if in == nil {
		return nil
	}
	out := new(WorkloadMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadOrchestration) DeepCopyInto(out *WorkloadOrchestration) {
	*out = *in
	if in.RepeatCount != nil {
		in, out := &in.RepeatCount, &out.RepeatCount
		*out = new(int32)
		**out = **in
	}
	if in.MaxConcurrent != nil {
		in, out := &in.MaxConcurrent, &out.MaxConcurrent
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadOrchestration.
func (in *WorkloadOrchestration) DeepCopy() *WorkloadOrchestration {
	if in == nil {
		return nil
	}
	out := new(WorkloadOrchestration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadReference) DeepCopyInto(out *WorkloadReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadReference.
func (in *WorkloadReference) DeepCopy() *WorkloadReference {
	if in == nil {
		return nil
	}
	out := new(WorkloadReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadRun) DeepCopyInto(out *WorkloadRun) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadRun.
func (in *WorkloadRun) DeepCopy() *WorkloadRun {
	if in == nil {
		return nil
	}
	out := new(WorkloadRun)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WorkloadRun) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadRunCheckpoint) DeepCopyInto(out *WorkloadRunCheckpoint) {
	*out = *in
	if in.StorageClassName != nil {
		in, out := &in.StorageClassName, &out.StorageClassName
		*out = new(string)
		**out = **in
	}
	if in.MaxRestarts != nil {
		in, out := &in.MaxRestarts, &out.MaxRestarts
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadRunCheckpoint.
func (in *WorkloadRunCheckpoint) DeepCopy() *WorkloadRunCheckpoint {
	if in == nil {
		return nil
	}
	out := new(WorkloadRunCheckpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadRunList) DeepCopyInto(out *WorkloadRunList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WorkloadRun, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadRunList.
func (in *WorkloadRunList) DeepCopy() *WorkloadRunList {
	if in == nil {
		return nil
	}
	out := new(WorkloadRunList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WorkloadRunList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadRunSpec) DeepCopyInto(out *WorkloadRunSpec) {
	*out = *in
	if in.Target != nil {
		in, out := &in.Target, &out.Target
		*out = new(TargetSpec)
		(*in).DeepCopyInto(*out)
	}
	in.Framework.DeepCopyInto(&out.Framework)
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(WorkloadConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.GpusPerNode != nil {
		in, out := &in.GpusPerNode, &out.GpusPerNode
		*out = new(int32)
		**out = **in
	}
	if in.MlnxPerNode != nil {
		in, out := &in.MlnxPerNode, &out.MlnxPerNode
		*out = new(int32)
		**out = **in
	}
	if in.NicResourceName != nil {
		in, out := &in.NicResourceName, &out.NicResourceName
		*out = new(string)
		**out = **in
	}
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]corev1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]corev1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Volumes != nil {
		in, out := &in.Volumes, &out.Volumes
		*out = make([]corev1.Volume, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.VolumeMounts != nil {
		in, out := &in.VolumeMounts, &out.VolumeMounts
		*out = make([]corev1.VolumeMount, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.EnableMNNVL != nil {
		in, out := &in.EnableMNNVL, &out.EnableMNNVL
		*out = new(bool)
		**out = **in
	}
	if in.Checkpoint != nil {
		in, out := &in.Checkpoint, &out.Checkpoint
		*out = new(WorkloadRunCheckpoint)
		(*in).DeepCopyInto(*out)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(corev1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.InitContainers != nil {
		in, out := &in.InitContainers, &out.InitContainers
		*out = make([]corev1.Container, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Orchestration != nil {
		in, out := &in.Orchestration, &out.Orchestration
		*out = new(WorkloadOrchestration)
		(*in).DeepCopyInto(*out)
	}
	if in.Thresholds != nil {
		in, out := &in.Thresholds, &out.Thresholds
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.GoodputMeasurement != nil {
		in, out := &in.GoodputMeasurement, &out.GoodputMeasurement
		*out = new(GoodputMeasurementConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.BandwidthMeasurement != nil {
		in, out := &in.BandwidthMeasurement, &out.BandwidthMeasurement
		*out = new(BandwidthMeasurementConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Overrides != nil {
		in, out := &in.Overrides, &out.Overrides
		*out = make([]OverrideSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.GangScheduler != nil {
		in, out := &in.GangScheduler, &out.GangScheduler
		*out = new(GangSchedulerSpec)
		**out = **in
	}
	if in.WorkloadMetadata != nil {
		in, out := &in.WorkloadMetadata, &out.WorkloadMetadata
		*out = new(WorkloadMetadata)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadRunSpec.
func (in *WorkloadRunSpec) DeepCopy() *WorkloadRunSpec {
	if in == nil {
		return nil
	}
	out := new(WorkloadRunSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadRunStatus) DeepCopyInto(out *WorkloadRunStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.WorkflowRef != nil {
		in, out := &in.WorkflowRef, &out.WorkflowRef
		*out = new(WorkflowReference)
		**out = **in
	}
	if in.SucceededNodesRef != nil {
		in, out := &in.SucceededNodesRef, &out.SucceededNodesRef
		*out = new(corev1.TypedLocalObjectReference)
		(*in).DeepCopyInto(*out)
	}
	if in.FailedNodesRef != nil {
		in, out := &in.FailedNodesRef, &out.FailedNodesRef
		*out = new(corev1.TypedLocalObjectReference)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadRunStatus.
func (in *WorkloadRunStatus) DeepCopy() *WorkloadRunStatus {
	if in == nil {
		return nil
	}
	out := new(WorkloadRunStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadSpec) DeepCopyInto(out *WorkloadSpec) {
	*out = *in
	if in.TrainJob != nil {
		in, out := &in.TrainJob, &out.TrainJob
		*out = new(trainerv1alpha1.TrainJobSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadSpec.
func (in *WorkloadSpec) DeepCopy() *WorkloadSpec {
	if in == nil {
		return nil
	}
	out := new(WorkloadSpec)
	in.DeepCopyInto(out)
	return out
}
